import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Define test vault path - normally this would be configurable, but setting a default for dev convenience
const TEST_VAULT_PATH = process.env.OBSIDIAN_TEST_VAULT || "/Users/plattnum/Obsidian-Vaults/plugin-dev-vault";
const PLUGIN_ID = "where-did-the-time-go";

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/closebrackets",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/comment",
        "@codemirror/fold",
        "@codemirror/gutter",
        "@codemirror/highlight",
        "@codemirror/history",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/matchbrackets",
        "@codemirror/panel",
        "@codemirror/rangeset",
        "@codemirror/rectangular-selection",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/stream-parser",
        "@codemirror/text",
        "@codemirror/tooltip",
        "@codemirror/view",
        ...builtins],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    plugins: [
        {
            name: 'copy-to-vault',
            setup(build) {
                build.onEnd(async () => {
                    // Always copy to test vault (both dev and prod)
                    if (TEST_VAULT_PATH) {
                        const pluginDir = path.join(TEST_VAULT_PATH, ".obsidian", "plugins", PLUGIN_ID);

                        try {
                            if (!fs.existsSync(pluginDir)) {
                                fs.mkdirSync(pluginDir, { recursive: true });
                            }

                            fs.copyFileSync("main.js", path.join(pluginDir, "main.js"));
                            fs.copyFileSync("manifest.json", path.join(pluginDir, "manifest.json"));
                            if (fs.existsSync("styles.css")) {
                                fs.copyFileSync("styles.css", path.join(pluginDir, "styles.css"));
                            }
                            console.log(`Plugin copied to ${pluginDir}`);
                        } catch (e) {
                            console.error("Failed to copy plugin to test vault:", e);
                        }
                    }
                });
            },
        },
    ],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();

    // Watch styles.css separately since it's not part of the JS build graph
    const pluginDir = path.join(TEST_VAULT_PATH, ".obsidian", "plugins", PLUGIN_ID);
    fs.watch("styles.css", (eventType) => {
        if (eventType === "change") {
            try {
                fs.copyFileSync("styles.css", path.join(pluginDir, "styles.css"));
                console.log("styles.css copied to vault");
            } catch (e) {
                console.error("Failed to copy styles.css:", e);
            }
        }
    });
}
